<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\torrent_island.ico</ApplicationIcon>
    <!-- <AssemblyName>TorrentIsland</AssemblyName> -->
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\torrent_island.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.6.14" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.10.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.11" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TorrentIsland.Infrastructure\TorrentIsland.Infrastructure.csproj" />
    <ProjectReference Include="..\TorrentIsland.Presentation.Console\TorrentIsland.Presentation.Console.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\torrent_island.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

	<ItemGroup>
		<None Update="Resources\mkvextract.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
