<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputPath>..\TorrentIsland.Presentation.Player\bin\Debug\net10.0-windows\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TorrentIsland.Application\TorrentIsland.Application.csproj" />
    <ProjectReference Include="..\TorrentIsland.Domain\TorrentIsland.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.10.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
    <PackageReference Include="MonoTorrent" Version="3.9.0-alpha.unstable.rev0000" />
    <PackageReference Include="Panlingo.LanguageIdentification.CLD2" Version="0.8.1" />
    <PackageReference Include="SharpCompress" Version="0.50.4" />
    <PackageReference Include="Spectre.Console" Version="0.57.2" />
    <PackageReference Include="SubtitlesParserV2" Version="2.4.0" />
    <PackageReference Include="YoutubeDLSharp" Version="1.2.0" />
  </ItemGroup>

</Project>
